# Generated by Django 5.0.6 on 2024-10-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('audio', models.FileField(upload_to='audios/', verbose_name='Audio')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
