# Generated by Django 5.0.6 on 2024-12-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='author',
            field=models.CharField(max_length=90, verbose_name='Autor'),
        ),
    ]
