# Generated by Django 5.0.6 on 2024-10-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_programep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
