# Generated by Django 5.0.6 on 2025-01-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pedidos_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data do programa')),
                ('color', models.CharField(choices=[('#005c81', 'Azul'), ('#d40f60', 'Rosa'), ('#f84339', 'Laranja'), ('#e79a32', 'Amarelo'), ('#368986', 'Verde'), ('#7345d6', 'Roxo'), ('#99b333', 'Verde-claro')], default='#005c81', max_length=7)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.program')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
