# Generated by Django 5.0.6 on 2025-01-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(verbose_name='Data do programa'),
        ),
    ]
