# Generated by Django 5.0.6 on 2025-01-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_calendar_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('aprovado', 'aprovado'), ('negado', 'negado'), ('pendente', 'pendente')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='singer',
            field=models.CharField(max_length=90, null=True, verbose_name='Artista/Banda'),
        ),
    ]
