# Generated by Django 5.0.6 on 2025-01-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_calendar_color_alter_pedidos_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='author',
            field=models.CharField(help_text='Digite seu nome', max_length=90, verbose_name='Seu Nome'),
        ),
    ]
