# Generated by Django 5.0.6 on 2025-01-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pedidos_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='author',
            field=models.CharField(max_length=90, verbose_name='Seu Nome'),
        ),
    ]
