# Generated by Django 5.0.6 on 2025-01-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pedidos_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningcard',
            name='is_auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
