# Generated by Django 5.0.6 on 2025-01-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_warningcard_is_auto_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='color',
        ),
        migrations.AddField(
            model_name='program',
            name='color',
            field=models.CharField(choices=[('#005c81', 'azul'), ('#d40f60', 'rosa'), ('#f84339', 'laranja'), ('#e79a32', 'amarelo'), ('#368986', 'verde'), ('#7345d6', 'roxo'), ('#99b333', 'verde-claro')], default='#005c81', max_length=7),
        ),
    ]
