# Generated by Django 5.0.6 on 2025-01-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_calendar_color_program_color'),
        ('app', 'group'),
    ]

    operations = [
    ]
