# Generated by Django 5.0.1 on 2024-03-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webradio', '0002_program_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-timestamp']},
        ),
    ]
