# Generated by Django 5.0.1 on 2024-03-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webradio', '0003_alter_program_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagem'),
        ),
    ]
